### ISSUE TITLE
Level 3 Toughened Spirits upgrade lists "Quick ()" as the effect

### ISSUE THREAD

**Issue by Adalace** [lmachens/soc.gg#105]
On the [Grand Armory page](https://www.soc.gg/buildings/Arleon/GrandArmory), the level 3 Toughened Spirits upgrade lists "Quick ()" as the effect. I don't know what that bonus is supposed to be, but "Quick ()" seems wrong.

![image](https://user-images.githubusercontent.com/3720037/208278355-49b61d9e-9e66-45a1-80c5-054981a397c6.png)

**Comment by lmachens** [comment]
Thx! Same issue with `Frightful`. Will be fixed soon
![image](https://user-images.githubusercontent.com/10058950/210070013-07b2d294-4e5d-4884-822f-3e14c32e4f33.png)
