### ISSUE TITLE
Pieces of untranslated text

### ISSUE THREAD

**Issue by rsgrava** [lmachens/soc.gg#15]
While the main content of the site is available in multiple languages, some text is hardcoded into english. This includes the sidebar, search button and some others like "learn more" in the factions page.

Example, when browsing the site in portuguese:

![image](https://user-images.githubusercontent.com/57885050/171295034-e7cd57d9-55ed-454f-9bbf-eeaddb0d884e.png)

**Comment by lmachens** [comment]
Right, most of the texts are from the in-game translations, but we will have some texts which we have to translate.
I would suggest creating a custom `terms.json` or `siteTerms.json` and extend the `getTerm` function.

In general, let's try to reduce the number of site terms to a minimum :).
