### ISSUE TITLE
Incomplete Skill Description for Essence Shield 

### ISSUE THREAD

**Issue by Daeruvan** [lmachens/soc.gg#17]
https://www.soc.gg/skills/PowerShielded

Missing description text for the benefits of essence shield (Range resistance)
![image](https://user-images.githubusercontent.com/4637248/171484030-fd7fc595-63e8-43e3-b06c-7ee3c86fbb1c.png)

**Comment by lmachens** [comment]
This is how it should look like

![image](https://user-images.githubusercontent.com/10058950/171635464-7f10e196-6715-4dc2-b564-f6e591429a80.png)
