### ISSUE TITLE
Add Links to Official Songs of Conquest website and Steam.

### ISSUE THREAD

**Issue by Daeruvan** [lmachens/soc.gg#18]
Should add links to the official game websites and store to promote the game

**Comment by rsgrava** [comment]
GoG store page and maybe the official game discord as well.

**Comment by lmachens** [comment]
👍
maybe on the landing page (#20) or on footer?

**Comment by 0x0014** [comment]
Is this up for grabs? If so I'd like to take this one on

If we want to drive traffic to SoC's main site, and whichever store fronts we want to highlight I think having the links in the footer would be best? Below is what I'm thinking in a rough mock up - sub out the text for the stores respective icons so it matches the header with Discord and Github icons, but open to whatever ya'll think is best

mobile view:
![soc-footer-mockup-mobile](https://user-images.githubusercontent.com/13407547/173475271-ec3f7dbe-63e0-4e9e-be2b-f1c22e471e18.png)

desktop:
![soc-footer-mockup](https://user-images.githubusercontent.com/13407547/173475280-1af56630-507e-4be0-8718-7359c3ff2d12.png)

**Comment by lmachens** [comment]
The footer will include more links like the privacy policies. I think, it might be difficult if the footer is always visible, because the size will increase.
What do you think about adding the footer at the bottom of the main area? The footer would be visible if you scroll down in the main area.
This allows us to have a multi line footer if required.
I like how the footer is added on https://mantine.dev/.

**Comment by 0x0014** [comment]
That's a much better implementation since we're going to have more than just the links to the stores in the footer. I'll get started implementing that

**Comment by lmachens** [comment]
Maybe we can call it "Official Discord"?
You can create a draft request (Work in progress) if you like and want to get early feedback.

**Comment by lmachens** [comment]
> What all links do we want in the footer? So far I have these:
> 
> * Steam store link
> * GoG store link
> * official website link
> 
> I'm unsure how to add their game discord in a way that differentiates itself from the Leon's Dev Discord in the header. Any ideas there?
> 
> Once we're solid on this I should have a PR opened up for this in the coming days

Hi, any update about the PR?

**Comment by 0x0014** [comment]
Sorry, been out sick and had an app launch that has eaten more time than expected. I should have a PR opened up for this this weekend. This is where I'm currently at with things, with links/layout open to redesign/adjustments for what ya'll think is best

![Screen Shot 2022-07-02 at 2 02 26 PM](https://user-images.githubusercontent.com/13407547/177014748-d7a8650b-0b81-429c-8880-03a7f4c18d53.png)

I'm not sure if we want to have icons in the bottom right there, but I included them for demo purposes.

Let me know if there are any links I'm missing or if there are any I should remove, same with verbiage.

**Comment by lmachens** [comment]
Looks good! 
I think we don't need the logo and "Songs of Conquest Database".
Same with icons, because we have them in header. Or we move them, but I like to have them prominent somewhere.

**Comment by 0x0014** [comment]
You thinking something more like this?

desktop:
![Screen Shot 2022-07-04 at 1 55 27 PM](https://user-images.githubusercontent.com/13407547/177211043-e41db559-02d5-4439-9054-a0f4544d684b.png)

mobile:
![Screen Shot 2022-07-04 at 1 56 41 PM](https://user-images.githubusercontent.com/13407547/177211134-fc00b888-2da9-4593-9121-674e33db3184.png)

**Comment by lmachens** [comment]
Looks good. Logo is not required I think, but it's up to you

**Comment by lmachens** [comment]
Fixed in #45
