### ISSUE TITLE
Some Skills have themselves as a requirement

### ISSUE THREAD

**Issue by Unei95** [lmachens/soc.gg#57]
An example for this is "March" on Sla-Kin.
![image](https://user-images.githubusercontent.com/19711897/179168639-d9de3e36-69ec-44fb-aa20-a36bb378fa61.png)

This problem already exists in the files produced by assetRipper
![image](https://user-images.githubusercontent.com/19711897/179168012-a0473cd7-8702-471a-bc8b-8c931e21342e.png)

I haven't checked in game whether or not skills showing this behavior are unobtainable.

**Comment by lmachens** [comment]
I am pretty sure this is an issue in game. I will ask the devs about it

**Comment by lmachens** [comment]
The devs approved that this is an issue in-game. It will be fixed soon 🤘
