### ISSUE TITLE
display skills as a tree

### ISSUE THREAD

**Issue by ikamensh** [lmachens/soc.gg#69]
It would be much quicker and easier to understand if skill dependencies were shown as a graph

**Comment by nightshadov** [comment]
currently there are 4 skillpools: Lvl1Pool, Lvl5Pool, Lvl10Pool and 8LevelPowerPool.
to make a tree graph, we have to assume:

1. same skills have same prerequisites in all pools
2. the graph is acyclic

we could then apply a topological sorting algorithm and visualize it like this:
https://observablehq.com/@erikbrinkman/d3-dag-topological

**Comment by lmachens** [comment]
`d3-dag` sounds promising, but sadly, the graphs have cycles and sometimes `or` and `and` connections.
Example for a cycle:
https://www.soc.gg/wielders/BaronAldus
`Brutal` and `Eager` results in a cycle.

I will test if we can bypass this issue.

**Comment by lmachens** [comment]
Some tests. Not sure how to solve or/and connections with this library :).
![image](https://user-images.githubusercontent.com/10058950/180662874-a975f297-b4f1-4ee9-b0ee-b00ed3fefc75.png)

**Comment by lmachens** [comment]
Visual guides are already added
